repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: check-added-large-files
        args: ["--maxkb=10000"]
      - id: check-json
      - id: pretty-format-json
        args: ["--autofix", "--indent=4", "--no-sort-keys"]
      - id: check-yaml
        args: [--allow-multiple-documents]
      - id: forbid-new-submodules
      - id: mixed-line-ending
        args: ["--fix=lf"]
      - id: trailing-whitespace
      - id: check-docstring-first
      - id: check-merge-conflict
      - id: detect-private-key

  - repo: https://github.com/asottile/pyupgrade
    rev: v3.16.0
    hooks:
      - id: pyupgrade
        entry: pyupgrade --py310-plus --keep-runtime-typing

  - repo: local
    hooks:
      - id: ruff
        name: ruff
        entry: ruff --fix .
        language: system
        pass_filenames: false
      - id: black
        name: black
        entry: black .
        language: system
        pass_filenames: false
      - id: pyright
        name: pyright
        entry: pyright .
        language: system
        pass_filenames: false
      - id: pytest
        name: pytest
        entry: |
          pytest
        language: system
        pass_filenames: false

exclude: '^requirements\.txt$'
